import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TrueSpeak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Load Preline after the page is interactive. Using CDN to ensure the file is served correctly. */}
        <Script
          src="https://unpkg.com/preline/dist/preline.js"
          strategy="afterInteractive"
        />

        {children}
        <footer className="text-center text-neutral-400 py-4">
          Made by Kamal Hussain © copyrights 2025
        </footer>
      </body>
    </html>
  );
}
